#!/bin/bash

#Load system global environment variables
source /etc/profile >/dev/null
#Read the installation location of the current application
InstallPath=$(dirname $(dirname $(readlink -f $0)))
#Switch the current location to the installation directory of the app
cd $InstallPath
project=TOS5_APP_HelloWorld
exec=./sbin/$project

service_start() {
    printf "Hello TOS APP: "
    local pid=$(pidof $project)
    if [ -z "$pid" ]; then
        $exec -D
        echo "starting"
    else
        echo "running"
    fi
}

service_stop() {
    local pid=$(pidof $project)
    if [ ! -z "$pid" ]; then
        kill $pid
    fi
    echo "$project stopped"
}

service_restart() {
    service_stop
    sleep 1s
    service_start
}

service_status() {
    local pid=$(pidof $project)
    if [ ! -z "$pid" ]; then
        echo "$project running"
    else
        echo "$project stopped"
    fi
}

case $1 in

start)
    service_start
    ;;
stop)
    service_stop
    ;;
restart)
    service_restart
    ;;
status)
    service_status
    ;;
*)
    echo "usage: name {start|stop|restart|status}"
    exit 1
    ;;
esac
exit $?